### ISSUE TITLE
Does this work on Sequelize object?

### ISSUE THREAD

**Issue by alexdrans** [miktam/sizeof#10]
I was wondering whether it's feasible to store a whole Sequelize object in Redis, and came across this module. When I attempt to measure the size of a Sequelize object, a whole core is used up, but no result is returned and the program just hangs (processing).

Any ideas why this might be occurring?

**Comment by miktam** [comment]
@alexdrans, sequelize provides `get()` method which if used without any parameters returns all values of the instance. Could you please try to use it and see if it would help?

**Comment by alexdrans** [comment]
Thanks mlktam, that worked! :+1:
