### ISSUE TITLE
Functions are objects too in javascript

### ISSUE THREAD

**Issue by gion** [miktam/sizeof#18]
Let's say we have the following case:

```
var fn = function() {}
fn.prop = 'value';
```

Your code wouldn't cache the `prop` size.

**Comment by Portur** [comment]
FYI https://stackoverflow.com/questions/1248302/how-to-get-the-size-of-a-javascript-object

**Comment by miktam** [comment]
Fixed here https://github.com/miktam/sizeof/pull/76
