### ISSUE TITLE
 there is no *.d.ts file to support typescript

### ISSUE THREAD

**Issue by abaddoncoder** [miktam/sizeof#22]
there is no *.d.ts file to support typescript

**Comment by toddobryan-clever** [comment]
Looks like this was done with https://github.com/miktam/sizeof/pull/23. Unfortunately, the typing provided doesn't seem to work for us. I've opened a new issue about that.

**Comment by miktam** [comment]
thank you, @toddobryan-clever, closing this for now
issue will be tracked with https://github.com/miktam/sizeof/issues/24
