### ISSUE TITLE
Deprecation warning if using with Node LTS (v12)

### ISSUE THREAD

**Issue by akirilyuk** [miktam/sizeof#46]
Hi, when using this package with the current Node LTS (v12) I get a deprecation warning:

(node:4278) [DEP0108] DeprecationWarning: zlib.bytesRead is deprecated and will change its meaning in the future. Use zlib.bytesWritten instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Any plans to fix this soon?

**Comment by miktam** [comment]
I believe this issue is already outdated. Nothing to fix.
