### ISSUE TITLE
Relative references must start with either "/", "./", or "../" giving runtime error when bundling with rollup.

### ISSUE THREAD

**Issue by emohankrishna** [miktam/sizeof#47]
**Uncaught (in promise) TypeError: Failed to resolve module specifier "buffer". Relative references must start with either "/", "./", or "../".**

I am facing the above issue at runtime but while bundling with rollup in react project it was not giving any issue.

**Comment by emohankrishna** [comment]
I checked the doc of buffer which is only dependency their mentioned "buffer/" while requiring instead of "buffer" to escape the conflict between node buffer module and npm node_module. This change worked for me.

**Comment by miktam** [comment]
Fixed in https://github.com/miktam/sizeof/pull/51
