### ISSUE TITLE
Recent deploy of 1.6.2 has breaking changes

### ISSUE THREAD

**Issue by RcrsvRyan** [miktam/sizeof#62]
Hello,

I just wanted to let you know that the recent minor version update from 1.6.1 to 1.6.2 has some breaking changes in certain node versions.

Specifically, I think the version bump of the buffer package from V5 to V6 has the breaking changes. I am seeing this line tagged as an error in the buffer package:

(buffer's index.js, line 1216): `this[++offset] * 2 ** 8 + `

With the error:

`SyntaxError: Unexpected token *`

I believe it is the use of `**` causing the above error. Would it be possible to revert the change and bump your Major version number up to 2 in order to undo the breaking change while still allowing your updates to be utilized by those who wish to do so?

**Comment by miktam** [comment]
@RcrsvRyan thank you!

Latest version should be fine, with the buffer version 5.7.x

**Comment by RcrsvRyan** [comment]
That looks good from my side. Thank you so much!
