### ISSUE TITLE
Different size in chrome and mozilla

### ISSUE THREAD

**Issue by mahsashadi** [miktam/sizeof#65]
Why `size-of` logs two different size in Chrome and Firefox, for a complicated object, by using `console.log()`.

```js
console.log('mywin size is:',  sizeof(win));

// Result:
mywin size is: 22923784    //logs in Chrome
mywin size is: 37458302    //logs in Firefox
```
@miktam

**Comment by agiangrant** [comment]
Firefox and Chrome are different browsers. Wouldn't that mean the Window object would also be different? I don't think we can expect the Window object to be the same size.
