### ISSUE TITLE
Function Support?

### ISSUE THREAD

**Issue by mahsashadi** [miktam/sizeof#66]
Does this module support functions?

**Comment by miktam** [comment]
@mahsashadi no, it doesn't. 
PR is always welcomed!

**Comment by miktam** [comment]
ChatGPT has a following view on calculating the function size

<img width="535" alt="chatGpt about function" src="https://user-images.githubusercontent.com/222522/215289141-182f4ca4-c8cb-4e4c-9ed9-427c98d987d7.png">


```
const util = require('util');
const myFunction = function() {console.log("Hello World")};

const funcString = util.inspect(myFunction);
const funcSize = Buffer.byteLength(funcString, 'utf8');
console.log(funcSize);
```
