### ISSUE TITLE
Question: V8

### ISSUE THREAD

**Issue by 360disrupt** [miktam/sizeof#7]
```
Please note, that V8 which compiles the JavaScript into native machine code, is not taken into account, as the compiled code is additionally heavily optimized
```
## Question
Does this mean that it always has less or equal size with V8?

## Background Info
I want to use this with nodejs to split outgoing requests into diff. requests to avoid `request size exceeds maximum` errors.

**Comment by miktam** [comment]
Good question! 
To answer that precisely, need to dig deeper into how optimizations are implemented.
Here is a high level description of Crankshaft, a compilation infrastructure for V8:
http://blog.chromium.org/2010/12/new-crankshaft-for-v8.html
