### ISSUE TITLE
Error Buffer Browser

### ISSUE THREAD

**Issue by Marius-Romanus** [miktam/sizeof#84]
Hi, sorry to always be the one to give you bad news :(
But Buffer doesn't exist in browser, only in Node. Runtime crash in the browser.

https://github.com/miktam/sizeof/blob/4979fc8bd8b26c709fb3e3537c394a7659ee06b9/indexv2.js#L62

https://github.com/miktam/sizeof/blob/4979fc8bd8b26c709fb3e3537c394a7659ee06b9/indexv2.js#L102

Greetings.

**Comment by miktam** [comment]
@Marius-Romanus there is no bad news, just feedback! 

Thank you. Hopefully, the latest version will fix this one.
